INSERT INTO employe (prenom,nom,machine,ip,tel,loginor) VALUES ('Annie','Guillochon','Nom-eb85c523610','10.211.14.32','19','afag');
INSERT INTO employe (prenom,nom,machine,ip,tel,loginor) VALUES ('Benjamin','Poulain','Benjamin','10.211.14.46','15','afbp');
INSERT INTO employe (prenom,nom,machine,ip,tel,loginor) VALUES ('Bernard','Taverson','ELEC1','10.211.14.23','25','afbt');
INSERT INTO employe (prenom,nom,machine,ip,tel,loginor) VALUES ('Charles','Gallic','Charlesxp','10.211.14.18','27','afcg');
INSERT INTO employe (prenom,nom,machine,ip,tel,loginor) VALUES ('Christophe','Le Henanff','Magasin2','10.211.14.17','','afclh');
INSERT INTO employe (prenom,nom,machine,ip,tel,loginor) VALUES ('Christophe','Le Moine','Magasin1','10.211.14.16','','afclm');
INSERT INTO employe (prenom,nom,machine,ip,tel,loginor) VALUES ('Claude','Kergosien','Receptionxp','10.211.14.24','16','afck');
INSERT INTO employe (prenom,nom,machine,ip,tel,loginor) VALUES ('Emilie','Le Nouail','CARO','10.211.14.20','20','afev');
INSERT INTO employe (prenom,nom,machine,ip,tel,loginor) VALUES ('Emmanuel','Le Mab','MCS1','10.211.14.28','17','afelm');
INSERT INTO employe (prenom,nom,machine,ip,tel,loginor) VALUES ('Ghislaine','Bellec','Ghis1','10.211.14.11','11','afgb');
INSERT INTO employe (prenom,nom,machine,ip,tel,loginor) VALUES ('Gilles','Haleza','','','','afgh');
INSERT INTO employe (prenom,nom,machine,ip,tel,loginor) VALUES ('Jean-Joseph','Richard','','','','afjjr');
INSERT INTO employe (prenom,nom,machine,ip,tel,loginor) VALUES ('Jean-René','Le Névé','Magasin1','10.211.14.16','','afjrln');
INSERT INTO employe (prenom,nom,machine,ip,tel,loginor) VALUES ('Jérémy','Morice','JERxp','10.211.14.21','21','afjm');
INSERT INTO employe (prenom,nom,machine,ip,tel,loginor) VALUES ('Jérome','Le Du','Jerome','10.211.14.15','','afjld');
INSERT INTO employe (prenom,nom,machine,ip,tel,loginor) VALUES ('Laurent','Geray','LG','10.211.14.19','18','aflg');
INSERT INTO employe (prenom,nom,machine,ip,tel,loginor) VALUES ('Laurent','Plunian','LP','','19','aflp');
INSERT INTO employe (prenom,nom,machine,ip,tel,loginor) VALUES ('Maëlle','Bellec','ASSIST1','10.211.14.12','10','afev');
INSERT INTO employe (prenom,nom,machine,ip,tel,loginor) VALUES ('Matthieu','Tranvaux','Matthieu','10.211.14.41','28','afmt');
INSERT INTO employe (prenom,nom,machine,ip,tel,loginor) VALUES ('Nicolas','Bonnin','Nicolas','10.211.14.40','15','afnb');
INSERT INTO employe (prenom,nom,machine,ip,tel,loginor) VALUES ('Pascal','Hervé','Reception2','10.211.14.30','16','afph');
INSERT INTO employe (prenom,nom,machine,ip,tel,loginor) VALUES ('Patricia','Kerzulec','Michel','10.211.14.14','12','afpk');
INSERT INTO employe (prenom,nom,machine,ip,tel,loginor) VALUES ('Stéphane','Le Neveu','Magasin2','10.211.14.17','','afjld');
INSERT INTO employe (prenom,nom,machine,ip,tel,loginor) VALUES ('Vivien','Noël','mcs-5lvejm6zano','10.211.14.38','26','afvn');
